### ISSUE TITLE
 Changing automatic emails

### ISSUE THREAD

**Issue by astro-monkey** [wiliamvj/Sistema-Classificados#1]
Where can I change automatic emails in the email footer?

Did not find the file for these changes.

**Comment by wiliamvj** [comment]
You must edit or edit the following files:

[application/models/Main_model.php](https://github.com/wiliamvj/Sistema-Classificados/blob/master/application/models/Main_model.php)

[admin/application/models/Panamerico_model.php](https://github.com/wiliamvj/Sistema-Classificados/blob/master/admin/application/models/Panamerico_model.php)

[admin/application/models/Main_model.php](https://github.com/wiliamvj/Sistema-Classificados/blob/master/admin/application/models/Main_model.php)

**Comment by astro-monkey** [comment]
Thank you!
